# Day 9: SQL + Data Analysis using Python, Pandas, and SQLite

This notebook demonstrates beginner-level data analysis by loading a dataset, inserting it into a local SQLite database, and running basic SQL queries using Pandas.

## 1. Import Libraries
We need `pandas` for data manipulation and `sqlite3` to interact with our local database.

In [1]:
import pandas as pd
import sqlite3

## 2. Load Dataset
Read the CSV file into a pandas DataFrame.

In [2]:
df = pd.read_csv("products.csv")

## 3. Display Basic Information
Check the first 5 rows, the dataset shape (number of rows and columns), and the column names.

In [3]:
print("Shape of dataset:", df.shape)
print("\nColumn names:", df.columns.tolist())

print("\nFirst 5 rows:")
df.head()

Shape of dataset: (1000, 13)

Column names: ['Index', 'Name', 'Description', 'Brand', 'Category', 'Price', 'Currency', 'Stock', 'EAN', 'Color', 'Size', 'Availability', 'Internal ID']

First 5 rows:

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95

## 4. Create SQLite Database and Table
We establish a connection to a database file named `products.db` (it will be created if it doesn't exist). Then, we store our pandas DataFrame into a SQL table named `products`.

In [4]:
conn = sqlite3.connect("products.db")
df.to_sql("products", conn, if_exists="replace", index=False)
print("Data successfully stored in 'products.db' database under the 'products' table.")

Data successfully stored in 'products.db' database under the 'products' table.

## 5. Execute SQL Queries

### a) View first 5 records
This query retrieves all columns for the first 5 records from the `products` table.
```sql
SELECT * FROM products LIMIT 5;
```

In [5]:
query_a = "SELECT * FROM products LIMIT 5;"
pd.read_sql(query_a, conn)

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95

### b) Select specific columns
This query selects only the `Name`, `Category`, and `Price` columns (showing just the first 5 results here for brevity).
```sql
SELECT Name, Category, Price
FROM products;
```

In [6]:
query_b = """
SELECT Name, Category, Price
FROM products;
"""
pd.read_sql(query_b, conn).head()

                                    Name                Category  Price
0                Thermostat Drone Heater      Kitchen Appliances     74
1  Ultra Speaker Iron Grill Advanced One       Fitness Equipment    510
2                Watch Headphones Kettle  Beauty & Personal Care    254
3  Portable Toaster Clock Monitor Silent                  Makeup     69
4                       Pro Toaster Oven              Automotive    525

### c) Use WHERE clause
This query filters the dataset to only include products with a price strictly greater than 200.
```sql
SELECT Name, Category, Price
FROM products
WHERE Price > 200;
```

In [7]:
query_c = """
SELECT Name, Category, Price
FROM products
WHERE Price > 200;
"""
pd.read_sql(query_c, conn).head()

                                     Name                Category  Price
0   Ultra Speaker Iron Grill Advanced One       Fitness Equipment    510
1                 Watch Headphones Kettle  Beauty & Personal Care    254
2                        Pro Toaster Oven              Automotive    525
3                 Mini Speakerphone Mixer             Team Sports    413
4  Eco Cooler Printer Speaker Prime Prime       Health & Wellness    621

### d) Use ORDER BY
This query retrieves the names, categories, and prices of products, sorting them by price in descending order (highest price first).
```sql
SELECT Name, Category, Price
FROM products
ORDER BY Price DESC;
```

In [8]:
query_d = """
SELECT Name, Category, Price
FROM products
ORDER BY Price DESC;
"""
pd.read_sql(query_d, conn).head()

                                      Name                Category  Price
0  Digital Clock Lock Eco Premium Portable         Office Supplies    999
1                 Ultra Cooker 360 Eco Pro             Smartphones    999
2        Fast Printer Fan Shaver Sense One  Beauty & Personal Care    999
3                    Webcam Projector Oven          Home & Kitchen    998
4       Premium Powerbank Radio Lite Prime                  Makeup    996

### e) Use GROUP BY with COUNT
This query groups the products by category and counts how many products belong to each category.
```sql
SELECT Category,
       COUNT(*) AS Product_Count
FROM products
GROUP BY Category;
```

In [9]:
query_e = """
SELECT Category,
       COUNT(*) AS Product_Count
FROM products
GROUP BY Category;
"""
pd.read_sql(query_e, conn).head()

                          Category  Product_Count
0  Accessories (Bags, Hats, Belts)             29
1                       Automotive             33
2           Beauty & Personal Care             29
3                   Bedding & Bath             16
4               Books & Stationery             39

### f) Use GROUP BY with AVG
This query calculates the average price per category and sorts the results so the category with the highest average price appears first.
```sql
SELECT Category,
       AVG(Price) AS Average_Price
FROM products
GROUP BY Category
ORDER BY Average_Price DESC;
```

In [10]:
query_f = """
SELECT Category,
       AVG(Price) AS Average_Price
FROM products
GROUP BY Category
ORDER BY Average_Price DESC;
"""
pd.read_sql(query_f, conn).head()

                 Category  Average_Price
0       Fitness Equipment     615.842105
1  Beauty & Personal Care     607.034483
2        Shoes & Footwear     603.206897
3             Smartphones     589.192308
4          Kids' Clothing     585.590909

## 6. Close the Database Connection
It is a best practice to close the connection to the database once you are done.

In [11]:
conn.close()
print("Database connection closed.")

Database connection closed.