# Day 11: Pivot and Merge Activity

In this notebook, we perform basic data reshaping and combining using Pandas `pivot_table` and `merge` functions.

## 1. Import Pandas and Load Data

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('products.csv')

# Fix the 'Price' column which might contain strings or commas from the raw data
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

## 2. Basic Dataset Information

In [3]:
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nFirst 5 rows:")
df.head()

Shape: (1000, 13)

Columns: ['Index', 'Name', 'Description', 'Brand', 'Category', 'Price', 'Currency', 'Stock', 'EAN', 'Color', 'Size', 'Availability', 'Internal ID']

First 5 rows:

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         1000 non-null   int64
 1   Name          1000 non-null   str
 2   Description   1000 non-null   str
 3   Brand         1000 non-null   str
 4   Category      1000 non-null   str
 5   Price         1000 non-null   int64
 6   Currency      1000 non-null   str
 7   Stock         1000 non-null   int64
 8   EAN           1000 non-null   int64
 9   Color         1000 non-null   str
 10  Size          1000 non-null   str
 11  Availability  1000 non-null   str
 12  Internal ID   1000 non-null   int64
dtypes: int64(5), str(8)
memory usage: 101.7 KB

---
## Part 1: Pivot Activity

**Explanation**: The pivot table below summarizes the average (mean) product price for each `Category`, broken down by product `Availability`.

In [5]:
pivot_table = pd.pivot_table(
    df,
    index="Category",
    columns="Availability",
    values="Price",
    aggfunc="mean"
)

pivot_table.head()

Availability,backorder,discontinued,in_stock,limited_stock,out_of_stock,pre_order
Category,,,,,,
"Accessories (Bags, Hats, Belts)",544.000000,676.000000,593.666667,153.5,429.500000,459.666667
Automotive,675.800000,540.428571,287.500000,366.6,372.333333,402.166667
Beauty & Personal Care,686.714286,284.000000,631.250000,522.0,556.500000,673.166667
Bedding & Bath,373.666667,590.666667,884.000000,309.5,382.333333,429.000000
Books & Stationery,479.555556,502.800000,364.000000,671.2,617.142857,318.500000

---
## Part 2: Merge Activity

Since we only have one dataset, we will create a manual `discount_df` to simulate joining two data sources.

In [6]:
discount_df = pd.DataFrame({
    "Category": ["Books & Stationery", "Kitchen Appliances", "Shoes & Footwear", "Kids' Clothing"],
    "Discount_Percentage": [10, 15, 20, 5]
})

merged_df = pd.merge(df, discount_df, on="Category", how="left")
merged_df.head(10)

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID,Discount_Percentage
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38,15.0
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27,NaN
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2,NaN
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94,NaN
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95,NaN
5,6,Mini Speakerphone Mixer,Tell figure discussion chair red keep tough.,Burton-Gould,Team Sports,413,USD,566,9016454988741,OliveDrab,Medium,out_of_stock,44,NaN
6,7,Eco Cooler Printer Speaker Prime Prime,Cover close myself camera red evening.,"Soto, Raymond and Doyle",Health & Wellness,621,USD,245,4116090222997,Moccasin,Extra Large,limited_stock,1,NaN
7,8,Webcam Trimmer Projector,Fear fight until market court worry security t...,"Padilla, Dunn and Pruitt",Laptops & Computers,414,USD,559,4970509402222,HoneyDew,XL,limited_stock,27,NaN
8,9,Silent Headphones Stove Wireless Air Clean,Truth gun Democrat commercial.,Hughes and Sons,Home & Kitchen,858,USD,525,4349285091157,Chocolate,5x7 in,discontinued,16,NaN
9,10,Wireless Charger Air Premium Ultra,Public security home.,Mcbride-Wyatt,Health & Wellness,153,USD,550,1301175488525,MediumPurple,S,in_stock,4,NaN

---
## Part 3: Final Output

We can display the final combined dataset and save it to a new CSV file.

In [7]:
merged_df.to_csv("day11_merged_products.csv", index=False)
print("Final merged DataFrame saved as 'day11_merged_products.csv'!")

merged_df.head()

Final merged DataFrame saved as 'day11_merged_products.csv'!

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID,Discount_Percentage
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38,15.0
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27,NaN
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2,NaN
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94,NaN
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95,NaN

---
## Conclusion
- **Pivot Table**: Used to summarize product prices category-wise. It is great for restructuring data to see multi-dimensional aggregations (like category vs availability).
- **Merge**: Used to combine product data with discount data based on the shared `Category` column. This is essential for joining related datasets from different sources.
- Both operations are foundational tools in data analysis.